<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild Condition="'$(Configuration)' == 'Debug'">true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" PrivateAssets="all" />
  </ItemGroup>
</Project>
